# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created: Sun Jun  3 22:14:37 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(780, 410)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(780, 400))
        Form.setMaximumSize(QtCore.QSize(780, 410))
        self.groupBoxInterfaceKit = QtGui.QGroupBox(Form)
        self.groupBoxInterfaceKit.setGeometry(QtCore.QRect(10, 10, 380, 380))
        self.groupBoxInterfaceKit.setObjectName(_fromUtf8("groupBoxInterfaceKit"))
        self.layoutWidget = QtGui.QWidget(self.groupBoxInterfaceKit)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 348, 261))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelAttached = QtGui.QLabel(self.layoutWidget)
        self.labelAttached.setObjectName(_fromUtf8("labelAttached"))
        self.gridLayout.addWidget(self.labelAttached, 0, 0, 1, 1)
        self.lineEditAttached = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditAttached.setObjectName(_fromUtf8("lineEditAttached"))
        self.gridLayout.addWidget(self.lineEditAttached, 0, 1, 1, 1)
        self.labelName = QtGui.QLabel(self.layoutWidget)
        self.labelName.setObjectName(_fromUtf8("labelName"))
        self.gridLayout.addWidget(self.labelName, 1, 0, 1, 1)
        self.labelSerial = QtGui.QLabel(self.layoutWidget)
        self.labelSerial.setObjectName(_fromUtf8("labelSerial"))
        self.gridLayout.addWidget(self.labelSerial, 2, 0, 1, 1)
        self.lineEditSerial = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditSerial.setObjectName(_fromUtf8("lineEditSerial"))
        self.gridLayout.addWidget(self.lineEditSerial, 2, 1, 1, 1)
        self.labelVersion = QtGui.QLabel(self.layoutWidget)
        self.labelVersion.setObjectName(_fromUtf8("labelVersion"))
        self.gridLayout.addWidget(self.labelVersion, 3, 0, 1, 1)
        self.lineEditVersion = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditVersion.setObjectName(_fromUtf8("lineEditVersion"))
        self.gridLayout.addWidget(self.lineEditVersion, 3, 1, 1, 1)
        self.labelDigiInputs = QtGui.QLabel(self.layoutWidget)
        self.labelDigiInputs.setObjectName(_fromUtf8("labelDigiInputs"))
        self.gridLayout.addWidget(self.labelDigiInputs, 4, 0, 1, 1)
        self.lineEditDigiInput = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditDigiInput.setObjectName(_fromUtf8("lineEditDigiInput"))
        self.gridLayout.addWidget(self.lineEditDigiInput, 4, 1, 1, 1)
        self.labelDigiOutputs = QtGui.QLabel(self.layoutWidget)
        self.labelDigiOutputs.setObjectName(_fromUtf8("labelDigiOutputs"))
        self.gridLayout.addWidget(self.labelDigiOutputs, 5, 0, 1, 1)
        self.lineEditDigiOutput = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditDigiOutput.setObjectName(_fromUtf8("lineEditDigiOutput"))
        self.gridLayout.addWidget(self.lineEditDigiOutput, 5, 1, 1, 1)
        self.labelAnalogInputs = QtGui.QLabel(self.layoutWidget)
        self.labelAnalogInputs.setObjectName(_fromUtf8("labelAnalogInputs"))
        self.gridLayout.addWidget(self.labelAnalogInputs, 6, 0, 1, 1)
        self.lineEditAnalogInput = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditAnalogInput.setObjectName(_fromUtf8("lineEditAnalogInput"))
        self.gridLayout.addWidget(self.lineEditAnalogInput, 6, 1, 1, 1)
        self.lineEditName = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditName.setObjectName(_fromUtf8("lineEditName"))
        self.gridLayout.addWidget(self.lineEditName, 1, 1, 1, 1)
        self.groupBoxDigiIn = QtGui.QGroupBox(Form)
        self.groupBoxDigiIn.setGeometry(QtCore.QRect(400, 10, 180, 90))
        self.groupBoxDigiIn.setObjectName(_fromUtf8("groupBoxDigiIn"))
        self.checkBox0 = QtGui.QCheckBox(self.groupBoxDigiIn)
        self.checkBox0.setGeometry(QtCore.QRect(10, 30, 21, 21))
        self.checkBox0.setText(_fromUtf8(""))
        self.checkBox0.setObjectName(_fromUtf8("checkBox0"))
        self.checkBox1 = QtGui.QCheckBox(self.groupBoxDigiIn)
        self.checkBox1.setGeometry(QtCore.QRect(30, 30, 21, 21))
        self.checkBox1.setText(_fromUtf8(""))
        self.checkBox1.setObjectName(_fromUtf8("checkBox1"))
        self.checkBox2 = QtGui.QCheckBox(self.groupBoxDigiIn)
        self.checkBox2.setGeometry(QtCore.QRect(50, 30, 21, 21))
        self.checkBox2.setText(_fromUtf8(""))
        self.checkBox2.setObjectName(_fromUtf8("checkBox2"))
        self.checkBox3 = QtGui.QCheckBox(self.groupBoxDigiIn)
        self.checkBox3.setGeometry(QtCore.QRect(70, 30, 21, 21))
        self.checkBox3.setText(_fromUtf8(""))
        self.checkBox3.setObjectName(_fromUtf8("checkBox3"))
        self.checkBox4 = QtGui.QCheckBox(self.groupBoxDigiIn)
        self.checkBox4.setGeometry(QtCore.QRect(90, 30, 21, 21))
        self.checkBox4.setText(_fromUtf8(""))
        self.checkBox4.setObjectName(_fromUtf8("checkBox4"))
        self.checkBox5 = QtGui.QCheckBox(self.groupBoxDigiIn)
        self.checkBox5.setGeometry(QtCore.QRect(110, 30, 21, 21))
        self.checkBox5.setText(_fromUtf8(""))
        self.checkBox5.setObjectName(_fromUtf8("checkBox5"))
        self.checkBox6 = QtGui.QCheckBox(self.groupBoxDigiIn)
        self.checkBox6.setGeometry(QtCore.QRect(130, 30, 21, 21))
        self.checkBox6.setText(_fromUtf8(""))
        self.checkBox6.setObjectName(_fromUtf8("checkBox6"))
        self.checkBox7 = QtGui.QCheckBox(self.groupBoxDigiIn)
        self.checkBox7.setGeometry(QtCore.QRect(150, 30, 21, 21))
        self.checkBox7.setText(_fromUtf8(""))
        self.checkBox7.setObjectName(_fromUtf8("checkBox7"))
        self.checkBox8 = QtGui.QCheckBox(self.groupBoxDigiIn)
        self.checkBox8.setGeometry(QtCore.QRect(10, 50, 21, 21))
        self.checkBox8.setText(_fromUtf8(""))
        self.checkBox8.setObjectName(_fromUtf8("checkBox8"))
        self.checkBox9 = QtGui.QCheckBox(self.groupBoxDigiIn)
        self.checkBox9.setGeometry(QtCore.QRect(30, 50, 21, 21))
        self.checkBox9.setText(_fromUtf8(""))
        self.checkBox9.setObjectName(_fromUtf8("checkBox9"))
        self.checkBox10 = QtGui.QCheckBox(self.groupBoxDigiIn)
        self.checkBox10.setGeometry(QtCore.QRect(50, 50, 21, 21))
        self.checkBox10.setText(_fromUtf8(""))
        self.checkBox10.setObjectName(_fromUtf8("checkBox10"))
        self.checkBox11 = QtGui.QCheckBox(self.groupBoxDigiIn)
        self.checkBox11.setGeometry(QtCore.QRect(70, 50, 21, 21))
        self.checkBox11.setText(_fromUtf8(""))
        self.checkBox11.setObjectName(_fromUtf8("checkBox11"))
        self.checkBox12 = QtGui.QCheckBox(self.groupBoxDigiIn)
        self.checkBox12.setGeometry(QtCore.QRect(90, 50, 21, 21))
        self.checkBox12.setText(_fromUtf8(""))
        self.checkBox12.setObjectName(_fromUtf8("checkBox12"))
        self.checkBox13 = QtGui.QCheckBox(self.groupBoxDigiIn)
        self.checkBox13.setGeometry(QtCore.QRect(110, 50, 21, 21))
        self.checkBox13.setText(_fromUtf8(""))
        self.checkBox13.setObjectName(_fromUtf8("checkBox13"))
        self.checkBox14 = QtGui.QCheckBox(self.groupBoxDigiIn)
        self.checkBox14.setGeometry(QtCore.QRect(130, 50, 21, 21))
        self.checkBox14.setText(_fromUtf8(""))
        self.checkBox14.setObjectName(_fromUtf8("checkBox14"))
        self.checkBox15 = QtGui.QCheckBox(self.groupBoxDigiIn)
        self.checkBox15.setGeometry(QtCore.QRect(150, 50, 21, 21))
        self.checkBox15.setText(_fromUtf8(""))
        self.checkBox15.setObjectName(_fromUtf8("checkBox15"))
        self.groupBoxDigiOut = QtGui.QGroupBox(Form)
        self.groupBoxDigiOut.setGeometry(QtCore.QRect(590, 10, 180, 90))
        self.groupBoxDigiOut.setObjectName(_fromUtf8("groupBoxDigiOut"))
        self.checkBox19 = QtGui.QCheckBox(self.groupBoxDigiOut)
        self.checkBox19.setGeometry(QtCore.QRect(70, 30, 21, 21))
        self.checkBox19.setText(_fromUtf8(""))
        self.checkBox19.setObjectName(_fromUtf8("checkBox19"))
        self.checkBox27 = QtGui.QCheckBox(self.groupBoxDigiOut)
        self.checkBox27.setGeometry(QtCore.QRect(70, 50, 21, 21))
        self.checkBox27.setText(_fromUtf8(""))
        self.checkBox27.setObjectName(_fromUtf8("checkBox27"))
        self.checkBox30 = QtGui.QCheckBox(self.groupBoxDigiOut)
        self.checkBox30.setGeometry(QtCore.QRect(130, 50, 21, 21))
        self.checkBox30.setText(_fromUtf8(""))
        self.checkBox30.setObjectName(_fromUtf8("checkBox30"))
        self.checkBox20 = QtGui.QCheckBox(self.groupBoxDigiOut)
        self.checkBox20.setGeometry(QtCore.QRect(90, 30, 21, 21))
        self.checkBox20.setText(_fromUtf8(""))
        self.checkBox20.setObjectName(_fromUtf8("checkBox20"))
        self.checkBox24 = QtGui.QCheckBox(self.groupBoxDigiOut)
        self.checkBox24.setGeometry(QtCore.QRect(10, 50, 21, 21))
        self.checkBox24.setText(_fromUtf8(""))
        self.checkBox24.setObjectName(_fromUtf8("checkBox24"))
        self.checkBox25 = QtGui.QCheckBox(self.groupBoxDigiOut)
        self.checkBox25.setGeometry(QtCore.QRect(30, 50, 21, 21))
        self.checkBox25.setText(_fromUtf8(""))
        self.checkBox25.setObjectName(_fromUtf8("checkBox25"))
        self.checkBox23 = QtGui.QCheckBox(self.groupBoxDigiOut)
        self.checkBox23.setGeometry(QtCore.QRect(150, 30, 21, 21))
        self.checkBox23.setText(_fromUtf8(""))
        self.checkBox23.setObjectName(_fromUtf8("checkBox23"))
        self.checkBox22 = QtGui.QCheckBox(self.groupBoxDigiOut)
        self.checkBox22.setGeometry(QtCore.QRect(130, 30, 21, 21))
        self.checkBox22.setText(_fromUtf8(""))
        self.checkBox22.setObjectName(_fromUtf8("checkBox22"))
        self.checkBox31 = QtGui.QCheckBox(self.groupBoxDigiOut)
        self.checkBox31.setGeometry(QtCore.QRect(150, 50, 21, 21))
        self.checkBox31.setText(_fromUtf8(""))
        self.checkBox31.setObjectName(_fromUtf8("checkBox31"))
        self.checkBox17 = QtGui.QCheckBox(self.groupBoxDigiOut)
        self.checkBox17.setGeometry(QtCore.QRect(30, 30, 21, 21))
        self.checkBox17.setText(_fromUtf8(""))
        self.checkBox17.setObjectName(_fromUtf8("checkBox17"))
        self.checkBox26 = QtGui.QCheckBox(self.groupBoxDigiOut)
        self.checkBox26.setGeometry(QtCore.QRect(50, 50, 21, 21))
        self.checkBox26.setText(_fromUtf8(""))
        self.checkBox26.setObjectName(_fromUtf8("checkBox26"))
        self.checkBox29 = QtGui.QCheckBox(self.groupBoxDigiOut)
        self.checkBox29.setGeometry(QtCore.QRect(110, 50, 21, 21))
        self.checkBox29.setText(_fromUtf8(""))
        self.checkBox29.setObjectName(_fromUtf8("checkBox29"))
        self.checkBox21 = QtGui.QCheckBox(self.groupBoxDigiOut)
        self.checkBox21.setGeometry(QtCore.QRect(110, 30, 21, 21))
        self.checkBox21.setText(_fromUtf8(""))
        self.checkBox21.setObjectName(_fromUtf8("checkBox21"))
        self.checkBox28 = QtGui.QCheckBox(self.groupBoxDigiOut)
        self.checkBox28.setGeometry(QtCore.QRect(90, 50, 21, 21))
        self.checkBox28.setText(_fromUtf8(""))
        self.checkBox28.setObjectName(_fromUtf8("checkBox28"))
        self.checkBox18 = QtGui.QCheckBox(self.groupBoxDigiOut)
        self.checkBox18.setGeometry(QtCore.QRect(50, 30, 21, 21))
        self.checkBox18.setText(_fromUtf8(""))
        self.checkBox18.setObjectName(_fromUtf8("checkBox18"))
        self.checkBox16 = QtGui.QCheckBox(self.groupBoxDigiOut)
        self.checkBox16.setGeometry(QtCore.QRect(10, 30, 21, 21))
        self.checkBox16.setText(_fromUtf8(""))
        self.checkBox16.setObjectName(_fromUtf8("checkBox16"))
        self.groupBoxAnalogIn = QtGui.QGroupBox(Form)
        self.groupBoxAnalogIn.setGeometry(QtCore.QRect(400, 110, 180, 120))
        self.groupBoxAnalogIn.setObjectName(_fromUtf8("groupBoxAnalogIn"))
        self.lineEditAnalogIn0 = QtGui.QLineEdit(self.groupBoxAnalogIn)
        self.lineEditAnalogIn0.setGeometry(QtCore.QRect(10, 30, 38, 20))
        self.lineEditAnalogIn0.setObjectName(_fromUtf8("lineEditAnalogIn0"))
        self.lineEditAnalogIn1 = QtGui.QLineEdit(self.groupBoxAnalogIn)
        self.lineEditAnalogIn1.setGeometry(QtCore.QRect(50, 30, 38, 20))
        self.lineEditAnalogIn1.setObjectName(_fromUtf8("lineEditAnalogIn1"))
        self.lineEditAnalogIn2 = QtGui.QLineEdit(self.groupBoxAnalogIn)
        self.lineEditAnalogIn2.setGeometry(QtCore.QRect(90, 30, 38, 20))
        self.lineEditAnalogIn2.setObjectName(_fromUtf8("lineEditAnalogIn2"))
        self.lineEditAnalogIn3 = QtGui.QLineEdit(self.groupBoxAnalogIn)
        self.lineEditAnalogIn3.setGeometry(QtCore.QRect(130, 30, 38, 20))
        self.lineEditAnalogIn3.setObjectName(_fromUtf8("lineEditAnalogIn3"))
        self.lineEditAnalogIn4 = QtGui.QLineEdit(self.groupBoxAnalogIn)
        self.lineEditAnalogIn4.setGeometry(QtCore.QRect(10, 52, 38, 20))
        self.lineEditAnalogIn4.setObjectName(_fromUtf8("lineEditAnalogIn4"))
        self.lineEditAnalogIn5 = QtGui.QLineEdit(self.groupBoxAnalogIn)
        self.lineEditAnalogIn5.setGeometry(QtCore.QRect(50, 52, 38, 20))
        self.lineEditAnalogIn5.setObjectName(_fromUtf8("lineEditAnalogIn5"))
        self.lineEditAnalogIn6 = QtGui.QLineEdit(self.groupBoxAnalogIn)
        self.lineEditAnalogIn6.setGeometry(QtCore.QRect(90, 52, 38, 20))
        self.lineEditAnalogIn6.setObjectName(_fromUtf8("lineEditAnalogIn6"))
        self.lineEditAnalogIn7 = QtGui.QLineEdit(self.groupBoxAnalogIn)
        self.lineEditAnalogIn7.setGeometry(QtCore.QRect(130, 52, 38, 20))
        self.lineEditAnalogIn7.setObjectName(_fromUtf8("lineEditAnalogIn7"))
        self.checkBoxRatiometric = QtGui.QCheckBox(self.groupBoxAnalogIn)
        self.checkBoxRatiometric.setGeometry(QtCore.QRect(10, 80, 100, 20))
        self.checkBoxRatiometric.setObjectName(_fromUtf8("checkBoxRatiometric"))
        self.groupBoxSensitivity = QtGui.QGroupBox(Form)
        self.groupBoxSensitivity.setGeometry(QtCore.QRect(590, 110, 181, 120))
        self.groupBoxSensitivity.setObjectName(_fromUtf8("groupBoxSensitivity"))
        self.sliderSensitivity = QtGui.QSlider(self.groupBoxSensitivity)
        self.sliderSensitivity.setGeometry(QtCore.QRect(10, 30, 160, 23))
        self.sliderSensitivity.setOrientation(QtCore.Qt.Horizontal)
        self.sliderSensitivity.setObjectName(_fromUtf8("sliderSensitivity"))
        self.lcdSensitivity = QtGui.QLCDNumber(self.groupBoxSensitivity)
        self.lcdSensitivity.setGeometry(QtCore.QRect(30, 60, 120, 41))
        self.lcdSensitivity.setFrameShape(QtGui.QFrame.Box)
        self.lcdSensitivity.setMidLineWidth(0)
        self.lcdSensitivity.setDigitCount(4)
        self.lcdSensitivity.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdSensitivity.setObjectName(_fromUtf8("lcdSensitivity"))
        self.groupBoxOutput = QtGui.QGroupBox(Form)
        self.groupBoxOutput.setGeometry(QtCore.QRect(400, 230, 370, 160))
        self.groupBoxOutput.setObjectName(_fromUtf8("groupBoxOutput"))
        self.textEditOutputLog = QtGui.QTextEdit(self.groupBoxOutput)
        self.textEditOutputLog.setGeometry(QtCore.QRect(10, 30, 350, 120))
        self.textEditOutputLog.setObjectName(_fromUtf8("textEditOutputLog"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxInterfaceKit.setTitle(QtGui.QApplication.translate("Form", "InterfaceKit info", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAttached.setText(QtGui.QApplication.translate("Form", "Attached", None, QtGui.QApplication.UnicodeUTF8))
        self.labelName.setText(QtGui.QApplication.translate("Form", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSerial.setText(QtGui.QApplication.translate("Form", "Serial no.", None, QtGui.QApplication.UnicodeUTF8))
        self.labelVersion.setText(QtGui.QApplication.translate("Form", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDigiInputs.setText(QtGui.QApplication.translate("Form", "Digital inputs", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDigiOutputs.setText(QtGui.QApplication.translate("Form", "Digital outputs", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAnalogInputs.setText(QtGui.QApplication.translate("Form", "Analog inputs", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxDigiIn.setTitle(QtGui.QApplication.translate("Form", "Digital inputs", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxDigiOut.setTitle(QtGui.QApplication.translate("Form", "Digital outputs", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxAnalogIn.setTitle(QtGui.QApplication.translate("Form", "Analog inputs", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxRatiometric.setText(QtGui.QApplication.translate("Form", "Ratiometric", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxSensitivity.setTitle(QtGui.QApplication.translate("Form", "Analog sensors sensitivity", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxOutput.setTitle(QtGui.QApplication.translate("Form", "Output", None, QtGui.QApplication.UnicodeUTF8))

